<a href="https://colab.research.google.com/github/xthimylJ/daily-practice/blob/main/workpaper_for_reviewing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 5th December

## reviewing `nn.Linear()`, `nn.ReLu()`

In [1]:
import torch
import numpy as np
import pandas as pd

In [2]:
torch.manual_seed(69)

In [3]:
torch.manual_seed(69)
w = torch.nn.Linear(in_features=5, out_features=4)
w.state_dict()

OrderedDict([('weight',
              tensor([[ 0.3039,  0.2720, -0.3387,  0.0277,  0.1473],
                      [-0.0825, -0.3678, -0.2300,  0.1837,  0.1088],
                      [ 0.3746, -0.4307,  0.3346, -0.3971,  0.4168],
                      [-0.4407, -0.1227, -0.0718,  0.1291, -0.4383]])),
             ('bias', tensor([0.0827, 0.4142, 0.1751, 0.3718]))])

In [4]:
w.weight

Parameter containing:
tensor([[ 0.3039,  0.2720, -0.3387,  0.0277,  0.1473],
        [-0.0825, -0.3678, -0.2300,  0.1837,  0.1088],
        [ 0.3746, -0.4307,  0.3346, -0.3971,  0.4168],
        [-0.4407, -0.1227, -0.0718,  0.1291, -0.4383]], requires_grad=True)

In [23]:
x = torch.randn(5)
x

tensor([-0.2146,  0.7220,  0.1815, -0.4670, -0.6243])

In [25]:
x.shape

torch.Size([5])

In [6]:
# manual multiplication

y = torch.matmul(x, w.weight.T) + w.bias
y

tensor([ 0.4802,  0.4862, -0.0169,  0.2141], grad_fn=<AddBackward0>)

In [7]:
# wrapping
y2 = w(x)
y2

tensor([ 0.4802,  0.4862, -0.0169,  0.2141], grad_fn=<ViewBackward0>)

In [8]:
#y1 = torch.matmul(x,w.weight) # here it will return an error

In [9]:
relu = torch.nn.ReLU()

In [10]:
relued_y2 = relu(y2) # I expect here a tensor of [0,  0.2930, 1.2792, 0]
relued_y2

tensor([0.4802, 0.4862, 0.0000, 0.2141], grad_fn=<ReluBackward0>)

In [11]:
torch.manual_seed(69)
# now x = matrix
x1 = torch.randn(5,5) # 5 datapoints, each has 5 features
x1

tensor([[-0.5300, -1.3035,  0.4438,  1.2221,  1.0395],
        [ 0.9608,  0.4214,  0.7452, -1.8389, -0.0036],
        [-0.5576, -1.0530,  0.6370,  1.3158, -0.4287],
        [ 1.9435, -0.8080, -0.7309,  0.6920, -0.3077],
        [-1.4196,  0.4929,  0.1217,  0.2247, -0.4807]])

In [12]:
y3 = torch.matmul(x1,w.weight.T)
y3

tensor([[-0.4791,  0.7587,  0.4593,  0.0638],
        [ 0.1029, -0.7438,  1.1566, -0.7646],
        [-0.6984,  0.4818, -0.2434,  0.6870],
        [ 0.5922,  0.3985,  0.4283, -0.4806],
        [-0.4031, -0.1032, -0.9929,  0.7961]], grad_fn=<MmBackward0>)

In [13]:
x1.shape

torch.Size([5, 5])

In [14]:
w.weight.T.shape

torch.Size([5, 4])

In [15]:
y3 = w(x1)
y3

tensor([[-0.3964,  1.1729,  0.6344,  0.4355],
        [ 0.1856, -0.3296,  1.3317, -0.3928],
        [-0.6156,  0.8960, -0.0683,  1.0587],
        [ 0.6749,  0.8127,  0.6034, -0.1088],
        [-0.3204,  0.3110, -0.8178,  1.1679]], grad_fn=<AddmmBackward0>)