<a href="https://colab.research.google.com/github/xthimylJ/daily-practice/blob/main/workpaper_for_reviewing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 5th December

## reviewing `nn.Linear()`

In [ ]:
import torch
import numpy as np
import pandas as pd

In [ ]:
torch.manual_seed(69)

In [ ]:
torch.manual_seed(69)
w = torch.nn.Linear(in_features=5, out_features=4)
w.state_dict()

OrderedDict([('weight',
              tensor([[ 0.3039,  0.2720, -0.3387,  0.0277,  0.1473],
                      [-0.0825, -0.3678, -0.2300,  0.1837,  0.1088],
                      [ 0.3746, -0.4307,  0.3346, -0.3971,  0.4168],
                      [-0.4407, -0.1227, -0.0718,  0.1291, -0.4383]])),
             ('bias', tensor([0.0827, 0.4142, 0.1751, 0.3718]))])

In [ ]:
w.weight

Parameter containing:
tensor([[ 0.3039,  0.2720, -0.3387,  0.0277,  0.1473],
        [-0.0825, -0.3678, -0.2300,  0.1837,  0.1088],
        [ 0.3746, -0.4307,  0.3346, -0.3971,  0.4168],
        [-0.4407, -0.1227, -0.0718,  0.1291, -0.4383]], requires_grad=True)

In [ ]:
x = torch.randn(5)
x

tensor([-0.3969, -0.0615,  0.8654, -0.7729,  1.5111])

In [ ]:
# manual multiplication

y = torch.matmul(x, w.weight.T) + w.bias
y

tensor([-0.1466,  0.2930,  1.2792, -0.2701], grad_fn=<AddBackward0>)

In [ ]:
# wrapping
y2 = w(x)
y2

tensor([-0.1466,  0.2930,  1.2792, -0.2701], grad_fn=<ViewBackward0>)

In [ ]:
#y1 = torch.matmul(x,w.weight) # here it will return an error

In [ ]:
relu = torch.nn.ReLU()

In [ ]:
relued_y2 = relu(y2) # I expect here a tensor of [0,  0.2930, 1.2792, 0]
relued_y2

tensor([0.0000, 0.2930, 1.2792, 0.0000], grad_fn=<ReluBackward0>)

In [ ]:
# now x = matrix
x1 = torch.randn(5,5)
x1

tensor([[-0.4224, -0.9932, -2.0695, -1.8343, -0.4817],
        [ 0.4692,  0.4951, -0.2140,  0.2282, -1.2322],
        [ 1.3270, -0.6450, -0.8438, -1.1487, -0.0070],
        [ 0.6390, -1.1000,  0.5087, -1.4697,  0.6544],
        [-0.5944,  0.5611, -0.1201,  0.0286,  0.3978]])

# 9th December

## reviewing the concept of linear combination

In [1]:
import numpy as np
import pandas as pd

In [5]:
v1 = np.random.randint(1,100, size=15)
c1 = 3
print(v1)

[38 79  6 87 93 87 58 56 57 11 98 87 59 49  2]


In [6]:
v2 = np.random.randint(1,100, size=15)
c2 = 4
print(v2)

[84 41  2 91 33 38 21 43 10 80 25 34 40 51 72]


In [15]:
v3 = np.random.randint(1,100, size=15)
c3 = 2
print(v3)

[98 92 60 86 28 27 18 44  2 85 37 36 47 88 59]


In [16]:
linear_combination = np.array(v1*c1 + v2*c2 + v3*c3)
print(linear_combination)

[646 585 146 797 467 467 294 428 215 523 468 469 431 527 412]


In [17]:
# as a matrix multiplication
feature_matrix = np.column_stack((v1,v2,v3))
feature_matrix # 15x3 shape

array([[38, 84, 98],
       [79, 41, 92],
       [ 6,  2, 60],
       [87, 91, 86],
       [93, 33, 28],
       [87, 38, 27],
       [58, 21, 18],
       [56, 43, 44],
       [57, 10,  2],
       [11, 80, 85],
       [98, 25, 37],
       [87, 34, 36],
       [59, 40, 47],
       [49, 51, 88],
       [ 2, 72, 59]])

In [22]:
# weight vector
weight_vector = np.array([c1,c2,c3])
print(weight_vector)
print(weight_vector.size)
print(weight_vector.T)
print(weight_vector.T.size)

[3 4 2]
3
[3 4 2]
3


In [24]:
# let's try to multiply feature matrix by the scalar vector
y = np.matmul(feature_matrix, weight_vector)
print(y)

[646 585 146 797 467 467 294 428 215 523 468 469 431 527 412]
